#!/bin/bash

#SBATCH --job-name=Mafft
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=10
#SBATCH --mem-per-cpu=10G
#SBATCH --time=6:00:00
#SBATCH --mail-type=begin
#SBATCH --mail-type=end


module load mafft
mafft --thread 10 /projects/mjolnir1/people/zpx817/PipeLineFolder/Bachelor/GalatheaResults_DSamples/RenamedGalathea/D_sampleAll.fasta >> D_SampleAlignment.txt

